/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf --transform 
Files: scene.gltf [1.91MB] > /Users/tylerj/Desktop/bloops-ai/public/models/scene-transformed.glb [38.25KB] (98%)
*/

import React, { useRef } from 'react'
import { useGLTF, OrthographicCamera } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <directionalLight intensity={0.7} decay={2} rotation={[-0.506, 0.629, 0.756]} scale={0.01} />
      <OrthographicCamera makeDefault={false} far={100000} near={0} position={[18.405, -8.945, 3.025]} rotation={[-0.117, 0.961, 0.096]} scale={0.01} />
      <mesh geometry={nodes.Shape_0.geometry} material={nodes.Shape_0.material} position={[10.199, 0, 0]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
